/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "question.h"

bool_t
xdr_qns_input (XDR *xdrs, qns_input *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ans, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qns_output (XDR *xdrs, qns_output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->rank))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->score))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->qsn, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->message, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clnt (XDR *xdrs, clnt *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->address))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ans, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->score))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rank))
		 return FALSE;
	return TRUE;
}
