/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUESTION_H_RPCGEN
#define _QUESTION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct qns_input {
	char ans[20];
};
typedef struct qns_input qns_input;

struct qns_output {
	int rank;
	int score;
	char qsn[200];
	char message[100];
};
typedef struct qns_output qns_output;

struct clnt {
	int address;
	char ans[15];
	int score;
	int index;
	int rank;
};
typedef struct clnt clnt;

#define QNS_PROG 0x13451111
#define QNS_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define qns_probe 1
extern  qns_output * qns_probe_1(qns_input *, CLIENT *);
extern  qns_output * qns_probe_1_svc(qns_input *, struct svc_req *);
#define qns_checkanswer 2
extern  qns_output * qns_checkanswer_1(qns_input *, CLIENT *);
extern  qns_output * qns_checkanswer_1_svc(qns_input *, struct svc_req *);
#define qns_getscore 3
extern  qns_output * qns_getscore_1(qns_input *, CLIENT *);
extern  qns_output * qns_getscore_1_svc(qns_input *, struct svc_req *);
#define qns_getrank 4
extern  qns_output * qns_getrank_1(qns_input *, CLIENT *);
extern  qns_output * qns_getrank_1_svc(qns_input *, struct svc_req *);
#define qns_exit 5
extern  qns_output * qns_exit_1(qns_input *, CLIENT *);
extern  qns_output * qns_exit_1_svc(qns_input *, struct svc_req *);
extern int qns_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define qns_probe 1
extern  qns_output * qns_probe_1();
extern  qns_output * qns_probe_1_svc();
#define qns_checkanswer 2
extern  qns_output * qns_checkanswer_1();
extern  qns_output * qns_checkanswer_1_svc();
#define qns_getscore 3
extern  qns_output * qns_getscore_1();
extern  qns_output * qns_getscore_1_svc();
#define qns_getrank 4
extern  qns_output * qns_getrank_1();
extern  qns_output * qns_getrank_1_svc();
#define qns_exit 5
extern  qns_output * qns_exit_1();
extern  qns_output * qns_exit_1_svc();
extern int qns_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_qns_input (XDR *, qns_input*);
extern  bool_t xdr_qns_output (XDR *, qns_output*);
extern  bool_t xdr_clnt (XDR *, clnt*);

#else /* K&R C */
extern bool_t xdr_qns_input ();
extern bool_t xdr_qns_output ();
extern bool_t xdr_clnt ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUESTION_H_RPCGEN */
