/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "question.h"

void
qns_prog_1(char *host)
{
	CLIENT *clnt;
	qns_output  *result_1;
	qns_input  qns_probe_1_arg;
	qns_output  *result_2;
	qns_input  qns_checkanswer_1_arg;
	qns_output  *result_3;
	qns_input  qns_getscore_1_arg;
	qns_output  *result_4;
	qns_input  qns_getrank_1_arg;
	qns_output  *result_5;
	qns_input  qns_exit_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, QNS_PROG, QNS_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
		char ans[20];
#endif	/* DEBUG */
int choice;
int flag = 0;
do{

	printf("Main Menu:\n");
	printf("1.Get question 2.Get score 3.Get rank 4.Quit 5.Get Answer\n");
	scanf("%d",&choice);
	switch(choice)
	{

		case 1:
		result_1 = qns_probe_1(&qns_probe_1_arg, clnt);
		if (result_1 == (qns_output *) NULL)
		{
			clnt_perror (clnt, "call failed");
		}
		printf("%s\n",result_1->qsn);
		break;
		case 4:
		result_5 = qns_exit_1(&qns_exit_1_arg, clnt);
		if (result_5 == (qns_output *) NULL) 
		{
			clnt_perror (clnt, "call failed");
		}
		printf("%s\n",result_5->message);
		flag = 1;			
		break;
		case 2:
		result_3 = qns_getscore_1(&qns_getscore_1_arg, clnt);
		if (result_3 == (qns_output *) NULL) 
		{
			clnt_perror (clnt, "call failed");
		}
		printf("%d\n",result_3->score);
		break;
		case 3:
		result_4 = qns_getrank_1(&qns_getrank_1_arg, clnt);
		if (result_4 == (qns_output *) NULL) 
		{
			clnt_perror (clnt, "call failed");
		}
		printf("%d\n",result_4->rank);
		break;
		case 5:
		printf("Please answer the question");
		scanf("%s",&qns_checkanswer_1_arg.ans);
		//strcat(qns_checkanswer_1_arg.ans,"\n");
		result_2 = qns_checkanswer_1(&qns_checkanswer_1_arg, clnt);
		if (result_2 == (qns_output *) NULL)
		{
			clnt_perror (clnt, "call failed");
		}
		printf("%s\n",result_2->message);
		break;
		default:
		printf("Wrong Choice");

	}
}while(choice<6 && flag ==0);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) 
	{
		printf ("usage: %s server_host choice\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	qns_prog_1 (host);
exit (0);
}
