/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "question.h"
#include <stdlib.h>
#include <stdio.h>

static int flag = 0;
static char *questions[50];
static char *answers[50];

qns_output *
qns_probe_1_svc(qns_input *argp, struct svc_req *rqstp)
{
	static qns_output result;
	int i=0;
	int j=0;
	if(flag == 0){	
	char ch;
	char qsn_file[100]="/home/HDUSER/Downloads/Agthu/Database-20180917/questions.txt";
	char ans_file[100]="/home/HDUSER/Downloads/Agthu/Database-20180917/answers.txt";
	FILE *qfp=fopen(qsn_file, "r");
	FILE *afp=fopen(ans_file, "r");
	if (qfp == NULL){
      		perror("Error while opening the file.\n");
      		exit(EXIT_FAILURE);
		}
	if (afp == NULL){
      		perror("Error while opening the file.\n");
      		exit(EXIT_FAILURE);
		}
	const size_t qline_size = 300;
	const size_t aline_size = 15;
	char qline[300];
	char* aline = malloc(aline_size);
	while (fgets(qline, qline_size, qfp) != NULL)  
	{
		questions[i]=*qline;
		//printf(questions[i]);
		i++;
	}

	while (fgets(aline, aline_size, afp) != NULL)  
	{
		answers[j]=aline;
		//printf(answers[j]);
		j++;
	}
	flag = 1;
	//free(aline);
	//free(qline);
	}

	for(int k = 0;k<50;k++){
	printf("%s",questions[k]);
	} 
	
	int index = (rand() % (49 - 0 + 1)) + 0; // rand_number%(upper_limit - lower_limit +1) + lower_limit
	printf("%d",index);
	//printf("%s",questions[index]);

	int clientaddr = rqstp->rq_xprt->xp_raddr.sin_addr.s_addr;
	printf("client address %u\n",clientaddr);
	//result.qsn = &questions[index];
	return &result;
}

qns_output *
qns_checkanswer_1_svc(qns_input *argp, struct svc_req *rqstp)
{
	static qns_output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

qns_output *
qns_getscore_1_svc(qns_input *argp, struct svc_req *rqstp)
{
	static qns_output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

qns_output *
qns_getrank_1_svc(qns_input *argp, struct svc_req *rqstp)
{
	static qns_output  result;

	/*
	 * insert server code here
	 */

	return &result;
}

qns_output *
qns_exit_1_svc(qns_input *argp, struct svc_req *rqstp)
{
	static qns_output  result;

	/*
	 * insert server code here
	 */

	return &result;
}


